
(function(global){'use strict';
function script(src){return new Promise((res,rej)=>{if(document.querySelector(`script[data-ssa-src="${src}"]`))return res();const s=document.createElement('script');s.src=src;s.dataset.ssaSrc=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function deps(){if(!global.turf)await script('https://cdn.jsdelivr.net/npm/@turf/turf@7.2.0/turf.min.js');if(!global.toGeoJSON)await script('https://cdn.jsdelivr.net/npm/@tmcw/togeojson@6.0.1/dist/togeojson.umd.js');if(!global.JSZip)await script('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js')}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
class SSAExplorerUI{
 constructor(o){this.o=o;this.maps=o.maps||(o.map?[o.map]:[]);this.master=o.masterMap||this.maps[0];this.container=o.container||this.master.getContainer();this.features=[];this.temp=[];this.mode=null;this.fill=true;this.markers=[];this.editMarkers=[];this.src='ssa-explorer-draw';this.ready=this.init()}
 async init(){await deps();this.build();this.maps.forEach(m=>m.loaded()?this.install(m):m.on('load',()=>this.install(m)));this.master.doubleClickZoom.disable();this.master.on('click',e=>this.click(e));this.master.on('dblclick',e=>{if(this.mode){e.preventDefault();this.finish()}});this.master.on('mousemove',e=>this.move(e));return this}
 install(m){if(!m.getSource(this.src))m.addSource(this.src,{type:'geojson',data:this.fc()});if(!m.getLayer('ssa-draw-halo'))m.addLayer({id:'ssa-draw-halo',type:'line',source:this.src,paint:{'line-color':'#000','line-width':7,'line-opacity':.38}});if(!m.getLayer('ssa-draw-fill'))m.addLayer({id:'ssa-draw-fill',type:'fill',source:this.src,filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#00e5ff','fill-opacity':this.fill?.22:0}});if(!m.getLayer('ssa-draw-line'))m.addLayer({id:'ssa-draw-line',type:'line',source:this.src,paint:{'line-color':'#00e5ff','line-width':4}});if(!m.getLayer('ssa-draw-points'))m.addLayer({id:'ssa-draw-points',type:'circle',source:this.src,filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':6,'circle-color':'#00e5ff','circle-stroke-color':'#111','circle-stroke-width':2}})}
 build(){const root=document.createElement('div');root.className='ssa-explorer';root.innerHTML=`<div class="ssa-rail">
 <button class="ssa-rail-btn" data-pane="layers"><span class="ico">▱</span><span>Layers</span></button>
 <button class="ssa-rail-btn" data-pane="identify"><span class="ico">ⓘ</span><span>Identify</span></button>
 <button class="ssa-rail-btn" data-pane="data"><span class="ico">＋</span><span>Data</span></button>
 <button class="ssa-rail-btn" data-pane="tools"><span class="ico">⌁</span><span>Use Tools</span></button>
 </div><div class="ssa-panel hidden"><div class="ssa-panel-head"><span class="ssa-title">Map tools</span><button class="ssa-close">×</button></div><div class="ssa-content"></div></div>`;this.container.appendChild(root);this.root=root;this.panel=root.querySelector('.ssa-panel');this.title=root.querySelector('.ssa-title');this.content=root.querySelector('.ssa-content');root.querySelectorAll('[data-pane]').forEach(b=>b.onclick=()=>this.open(b.dataset.pane));root.querySelector('.ssa-close').onclick=()=>this.close()}
 open(p){this.pane=p;this.panel.classList.remove('hidden');this.root.querySelectorAll('[data-pane]').forEach(b=>b.classList.toggle('active',b.dataset.pane===p));if(p==='tools')this.tools();if(p==='layers')this.layers();if(p==='identify')this.identify();if(p==='data')this.data()}
 close(){this.panel.classList.add('hidden');this.root.querySelectorAll('[data-pane]').forEach(b=>b.classList.remove('active'))}
 layers(){this.title.textContent='Layers & view';const layerOpts=(this.o.layers||[]).map(x=>`<option value="${x.id}" ${x.active?'selected':''}>${x.label}</option>`).join('');this.content.innerHTML=`<div class="ssa-panel-body"><div class="ssa-field"><label>Basemap</label><div class="ssa-subrow"><button class="ssa-chip" data-base="map">Map</button><button class="ssa-chip active" data-base="satellite">Satellite</button></div></div>${layerOpts?`<div class="ssa-field"><label>Imagery</label><select class="ssa-layer-select">${layerOpts}</select></div>`:''}<div class="ssa-field"><label>Opacity</label><input class="ssa-opacity" type="range" min="0" max="100" value="100"></div><div class="ssa-subrow"><button class="ssa-chip ssa-fit">Fit survey</button>${this.o.backUrl?`<button class="ssa-chip ssa-back">Back</button>`:''}</div></div>`;this.content.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{this.content.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('active',x===b));this.o.setBasemap?.(b.dataset.base)});const sel=this.content.querySelector('.ssa-layer-select');if(sel)sel.onchange=()=>this.o.setLayer?.(sel.value);this.content.querySelector('.ssa-opacity').oninput=e=>this.o.setOpacity?.(Number(e.target.value)/100);this.content.querySelector('.ssa-fit').onclick=()=>this.o.fit?.();const back=this.content.querySelector('.ssa-back');if(back)back.onclick=()=>location.href=this.o.backUrl}
 identify(){this.title.textContent='Identify';this.content.innerHTML='<div class="ssa-panel-body"><div class="ssa-readout">Click the map to identify coordinates.</div></div>';this.identifying=true}
 data(){this.title.textContent='Add / export data';this.content.innerHTML=`<div class="ssa-panel-body"><div class="ssa-tool-grid"><label class="ssa-tool ssa-file"><span class="ssa-tool-icon">⇧</span>Import<input type="file" accept=".kml,.kmz,.geojson,.json"></label><button class="ssa-tool" data-exp="kml"><span class="ssa-tool-icon">K</span>Export KML</button><button class="ssa-tool" data-exp="geo"><span class="ssa-tool-icon">G</span>Export GeoJSON</button></div><div class="ssa-readout">Import KML, KMZ or GeoJSON into the current map. Imported geometry can then be measured or edited.</div></div>`;this.content.querySelector('input').onchange=e=>this.importFile(e.target.files[0]);this.content.querySelector('[data-exp=kml]').onclick=()=>this.exportKML();this.content.querySelector('[data-exp=geo]').onclick=()=>this.exportJSON()}
 tools(){this.title.textContent='Use map tools';this.content.innerHTML=`<div class="ssa-tabs"><button class="ssa-tab active" data-tab="measure">Measure</button><button class="ssa-tab" data-tab="analyse">Analyse</button><button class="ssa-tab" data-tab="sketch">Sketch</button></div><div class="ssa-panel-body ssa-tool-body"></div>`;this.content.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.content.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));this.renderTab(b.dataset.tab)});this.renderTab('measure')}
 renderTab(tab){const body=this.content.querySelector('.ssa-tool-body');if(tab==='measure'){body.innerHTML=this.grid([{id:'length',icon:'↔',label:'Length'},{id:'measure-area',icon:'▱',label:'Area'},{id:'radius',icon:'◉',label:'Radius'}])+this.common();}else if(tab==='analyse'){body.innerHTML=this.grid([{id:'swipe',icon:'◫',label:'Swipe',disabled:!this.o.swipe},{id:'shadow',icon:'◩',label:'Shadow',disabled:true,title:'Requires elevation/DSM support'},{id:'los',icon:'◨',label:'Line Sight',disabled:true,title:'Requires elevation/DSM support'}])+`<div class="ssa-readout">Swipe is available where repeat survey dates exist. Shadow and Line Sight are reserved for a future DSM/elevation layer so they are not faked with flat-map maths.</div>`;}else{body.innerHTML=this.grid([{id:'label',icon:'T',label:'Label'},{id:'pin',icon:'⌖',label:'Pin'},{id:'line',icon:'⌟',label:'Line'},{id:'polygon',icon:'▱',label:'Polygon'},{id:'rectangle',icon:'□',label:'Rectangle'},{id:'circle',icon:'○',label:'Circle'}])+this.common();}body.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>this.tool(b.dataset.tool));body.querySelector('.ssa-fill')?.addEventListener('click',e=>{this.fill=!this.fill;e.currentTarget.textContent='Shading: '+(this.fill?'On':'Off');e.currentTarget.classList.toggle('active',this.fill);this.maps.forEach(m=>m.getLayer('ssa-draw-fill')&&m.setPaintProperty('ssa-draw-fill','fill-opacity',this.fill?.22:0))});body.querySelector('.ssa-finish')?.addEventListener('click',()=>this.finish());body.querySelector('.ssa-edit')?.addEventListener('click',()=>this.edit());body.querySelector('.ssa-undo')?.addEventListener('click',()=>this.undo());body.querySelector('.ssa-clear')?.addEventListener('click',()=>this.clear())}
 grid(items){return `<div class="ssa-tool-grid">${items.map(x=>`<button class="ssa-tool" data-tool="${x.id}" ${x.disabled?'disabled':''} title="${x.title||''}"><span class="ssa-tool-icon">${x.icon}</span>${x.label}</button>`).join('')}</div>`}
 common(){return `<div class="ssa-subrow"><button class="ssa-chip ssa-fill active">Shading: ${this.fill?'On':'Off'}</button><button class="ssa-chip ssa-finish">Finish</button><button class="ssa-chip ssa-edit">Edit</button><button class="ssa-chip ssa-undo">Undo</button><button class="ssa-chip ssa-clear">Clear</button></div><div class="ssa-readout">Choose a tool.</div>`}
 tool(t){if(t==='swipe'){this.o.swipe?.();return}if(t==='label'){const txt=prompt('Label text');if(!txt)return;this.pendingLabel=txt;this.mode='label';this.setRead('Click map to place label.');return}this.mode=t;this.temp=[];this.removeEdit();this.setRead(t==='rectangle'||t==='circle'||t==='radius'?'Click the first point, then the second.':'Click points on the map. Double-click or Finish to complete.');this.sync()}
 setRead(x){const r=this.content.querySelector('.ssa-readout');if(r)r.innerHTML=x}
 click(e){if(this.identifying){this.identifying=false;this.setRead(`Longitude <b>${e.lngLat.lng.toFixed(6)}</b><br>Latitude <b>${e.lngLat.lat.toFixed(6)}</b>`);return}if(!this.mode)return;const c=[e.lngLat.lng,e.lngLat.lat];if(this.mode==='pin'){this.features.push(turf.point(c,{kind:'pin'}));this.addPin(c);this.mode=null;this.sync();return}if(this.mode==='label'){this.features.push(turf.point(c,{kind:'label',label:this.pendingLabel}));this.addLabel(c,this.pendingLabel);this.mode=null;this.sync();return}this.temp.push(c);if(['rectangle','circle','radius'].includes(this.mode)&&this.temp.length===2)this.finish();else{this.sync();this.readTemp(this.temp)}}
 move(e){if(!this.mode||!this.temp.length)return;const t=[...this.temp,[e.lngLat.lng,e.lngLat.lat]];this.readTemp(t)}
 finish(){if(!this.mode)return;const c=this.temp;if((this.mode==='length'||this.mode==='line')&&c.length>=2)this.features.push(turf.lineString(c,{kind:this.mode}));else if((this.mode==='measure-area'||this.mode==='polygon')&&c.length>=3){const r=[...c,c[0]];this.features.push(turf.polygon([r],{kind:this.mode}))}else if(this.mode==='rectangle'&&c.length>=2){const a=c[0],b=c[1];this.features.push(turf.polygon([[[a[0],a[1]],[b[0],a[1]],[b[0],b[1]],[a[0],b[1]],[a[0],a[1]]]],{kind:'rectangle'}))}else if((this.mode==='circle'||this.mode==='radius')&&c.length>=2){const km=turf.distance(turf.point(c[0]),turf.point(c[1]),{units:'kilometers'});this.features.push(turf.circle(c[0],km,{steps:96,units:'kilometers',properties:{kind:this.mode,radiusKm:km}}))}else return;const f=this.features[this.features.length-1];this.mode=null;this.temp=[];this.sync();this.setRead(this.describe(f))}
 undo(){if(this.temp.length){this.temp.pop();this.sync();this.readTemp(this.temp)}else if(this.features.length){this.features.pop();this.sync()}}
 clear(){this.features=[];this.temp=[];this.mode=null;this.markers.forEach(m=>m.remove());this.markers=[];this.removeEdit();this.sync();this.setRead('Cleared.')}
 readTemp(c){if(!c.length)return;if(this.mode==='length')this.setRead(this.dist(c));if(this.mode==='measure-area'&&c.length>=3)this.setRead(this.areaCoords(c));if(this.mode==='radius'&&c.length>=2){const km=turf.distance(c[0],c[c.length-1],{units:'kilometers'});this.setRead(`<b>Radius ${km<1?(km*1000).toFixed(1)+' m':km.toFixed(3)+' km'}</b><br>Area ${(Math.PI*km*km*100).toFixed(3)} ha`)}}
 dist(c){const km=turf.length(turf.lineString(c),{units:'kilometers'});return `<b>${km<1?(km*1000).toFixed(1)+' m':km.toFixed(3)+' km'}</b>`}
 areaCoords(c){const r=[...c,c[0]],p=turf.polygon([r]),sqm=turf.area(p),per=turf.length(turf.polygonToLine(p),{units:'kilometers'});return `<b>${(sqm/10000).toFixed(3)} ha</b><br>${sqm.toFixed(0)} m² · perimeter ${per<1?(per*1000).toFixed(0)+' m':per.toFixed(2)+' km'}`}
 describe(f){if(f.properties?.radiusKm){const km=f.properties.radiusKm;return `<b>Radius ${km<1?(km*1000).toFixed(1)+' m':km.toFixed(3)+' km'}</b><br>Area ${(Math.PI*km*km*100).toFixed(3)} ha`}if(f.geometry.type==='LineString')return this.dist(f.geometry.coordinates);if(f.geometry.type==='Polygon')return this.areaCoords(f.geometry.coordinates[0].slice(0,-1));return 'Feature created.'}
 fc(){const fs=[...this.features];if(['length','line'].includes(this.mode)&&this.temp.length>=2)fs.push(turf.lineString(this.temp,{preview:true}));if(['measure-area','polygon'].includes(this.mode)&&this.temp.length>=2)fs.push(turf.lineString(this.temp,{preview:true}));this.temp.forEach(c=>fs.push(turf.point(c,{preview:true})));return turf.featureCollection(fs)}
 sync(){const d=this.fc();this.maps.forEach(m=>{const s=m.getSource(this.src);if(s)s.setData(d)})}
 addPin(c){this.maps.forEach(m=>{const e=document.createElement('div');e.className='ssa-pin-marker';const mk=new maplibregl.Marker({element:e}).setLngLat(c).addTo(m);this.markers.push(mk)})}
 addLabel(c,t){this.maps.forEach(m=>{const e=document.createElement('div');e.className='ssa-label-marker';e.textContent=t;const mk=new maplibregl.Marker({element:e}).setLngLat(c).addTo(m);this.markers.push(mk)})}
 edit(){this.removeEdit();const f=[...this.features].reverse().find(x=>x.geometry.type==='Polygon');if(!f){this.setRead('No polygon available to edit.');return}const ring=f.geometry.coordinates[0].slice(0,-1);ring.forEach((c,i)=>{const e=document.createElement('div');e.style.cssText='width:14px;height:14px;border-radius:50%;background:#00e5ff;border:2px solid #111;cursor:move';const mk=new maplibregl.Marker({element:e,draggable:true}).setLngLat(c).addTo(this.master);mk.on('drag',()=>{const p=mk.getLngLat();ring[i]=[p.lng,p.lat];f.geometry.coordinates[0]=[...ring,ring[0]];this.sync();this.setRead(this.describe(f))});this.editMarkers.push(mk)});this.setRead('Drag cyan vertices to edit.')}
 removeEdit(){(this.editMarkers||[]).forEach(m=>m.remove());this.editMarkers=[]}
 async importFile(file){if(!file)return;try{let g,n=file.name.toLowerCase();if(n.endsWith('.geojson')||n.endsWith('.json'))g=JSON.parse(await file.text());else if(n.endsWith('.kml'))g=toGeoJSON.kml(new DOMParser().parseFromString(await file.text(),'text/xml'));else if(n.endsWith('.kmz')){const z=await JSZip.loadAsync(await file.arrayBuffer()),k=Object.keys(z.files).find(x=>x.toLowerCase().endsWith('.kml'));if(!k)throw Error('KMZ contains no KML');g=toGeoJSON.kml(new DOMParser().parseFromString(await z.files[k].async('text'),'text/xml'))}else throw Error('Unsupported format');const fs=g.type==='FeatureCollection'?g.features:[g];this.features.push(...fs.filter(x=>x&&x.geometry));this.sync();const bb=turf.bbox(turf.featureCollection(this.features));this.master.fitBounds([[bb[0],bb[1]],[bb[2],bb[3]]],{padding:50,maxZoom:19});this.setRead(`Imported ${fs.length} feature${fs.length===1?'':'s'}.`)}catch(e){this.setRead('Import failed: '+e.message)}}
 exportJSON(){if(!this.features.length)return;dl(new Blob([JSON.stringify(turf.featureCollection(this.features),null,2)],{type:'application/geo+json'}),(this.o.fileNameBase||'map-layer')+'.geojson')}
 exportKML(){if(!this.features.length)return;const pm=this.features.map((f,i)=>{const nm=esc(f.properties?.label||f.properties?.name||`Feature ${i+1}`);if(f.geometry.type==='Point'){const c=f.geometry.coordinates;return `<Placemark><name>${nm}</name><Point><coordinates>${c[0]},${c[1]},0</coordinates></Point></Placemark>`}if(f.geometry.type==='LineString')return `<Placemark><name>${nm}</name><LineString><coordinates>${f.geometry.coordinates.map(c=>`${c[0]},${c[1]},0`).join(' ')}</coordinates></LineString></Placemark>`;if(f.geometry.type==='Polygon')return `<Placemark><name>${nm}</name><Polygon><outerBoundaryIs><LinearRing><coordinates>${f.geometry.coordinates[0].map(c=>`${c[0]},${c[1]},0`).join(' ')}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>`;return ''}).join('');dl(new Blob([`<?xml version="1.0"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>${pm}</Document></kml>`],{type:'application/vnd.google-earth.kml+xml'}),(this.o.fileNameBase||'map-layer')+'.kml')}
}
global.SSAExplorerUI=SSAExplorerUI;
})(window);
