(function(g){'use strict';
function load(src,key){return new Promise((ok,no)=>{if(document.querySelector('script[data-ssa="'+key+'"]'))return ok();const s=document.createElement('script');s.src=src;s.dataset.ssa=key;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function deps(){if(!g.turf)await load('https://cdn.jsdelivr.net/npm/@turf/turf@7.2.0/turf.min.js','turf');if(!g.toGeoJSON)await load('https://cdn.jsdelivr.net/npm/@tmcw/togeojson@6.0.1/dist/togeojson.umd.js','togeojson');if(!g.JSZip)await load('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','jszip')}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},700)}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
class SSAMapTools{
 constructor(o){this.maps=o.maps||[o.map];this.master=o.masterMap||this.maps[0];this.container=o.container||this.master.getContainer();this.base=o.fileNameBase||'map-layer';this.mode=null;this.coords=[];this.features=[];this.markers=[];this.src='ssa-tools-src';this.ready=this.init()}
 async init(){await deps();this.ui();this.maps.forEach(m=>m.loaded()?this.install(m):m.on('load',()=>this.install(m)));this.master.on('click',e=>this.click(e));this.master.on('dblclick',e=>{if(this.mode){e.preventDefault();this.finish()}});this.master.doubleClickZoom.disable();this.master.on('mousemove',e=>this.move(e));return this}
 install(m){if(!m.getSource(this.src))m.addSource(this.src,{type:'geojson',data:this.fc()});if(!m.getLayer('ssa-tools-fill'))m.addLayer({id:'ssa-tools-fill',type:'fill',source:this.src,filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#1f6f43','fill-opacity':.18}});if(!m.getLayer('ssa-tools-line'))m.addLayer({id:'ssa-tools-line',type:'line',source:this.src,paint:{'line-color':'#ffb000','line-width':3}});if(!m.getLayer('ssa-tools-pts'))m.addLayer({id:'ssa-tools-pts',type:'circle',source:this.src,filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':5,'circle-color':'#ffb000','circle-stroke-color':'#fff','circle-stroke-width':2}})}
 ui(){const b=document.createElement('div');b.className='ssa-tools';b.innerHTML=`<div class="ssa-tools__head"><span>Map tools</span><button class="ssa-tools__toggle">Minimise</button></div><div class="ssa-tools__body"><button data-mode="distance">Distance</button><button data-mode="area">Area</button><button data-act="finish">Finish</button><button data-act="edit">Edit area</button><label class="ssa-file">Import<input data-act="import" type="file" accept=".kml,.kmz,.geojson,.json"></label><button data-act="kml">Export KML</button><button data-act="json">Export GeoJSON</button><button data-act="undo">Undo</button><button data-act="clear" class="danger">Clear</button><div class="ssa-tools__readout">Choose Distance or Area.</div><div class="ssa-tools__hint">Distance supports multiple segments. Area reports hectares, m² and perimeter. Import supports KML, KMZ and GeoJSON.</div></div>`;this.container.appendChild(b);this.box=b;this.read=b.querySelector('.ssa-tools__readout');b.querySelector('.ssa-tools__toggle').onclick=()=>{b.classList.toggle('collapsed');b.querySelector('.ssa-tools__toggle').textContent=b.classList.contains('collapsed')?'Tools':'Minimise'};b.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>this.setMode(x.dataset.mode));b.querySelector('[data-act=finish]').onclick=()=>this.finish();b.querySelector('[data-act=edit]').onclick=()=>this.edit();b.querySelector('[data-act=undo]').onclick=()=>this.undo();b.querySelector('[data-act=clear]').onclick=()=>this.clear();b.querySelector('[data-act=kml]').onclick=()=>this.exportKML();b.querySelector('[data-act=json]').onclick=()=>this.exportJSON();b.querySelector('[data-act=import]').onchange=e=>this.importFile(e.target.files[0])}
 setMode(m){this.mode=m;this.coords=[];this.rmMarkers();this.box.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));this.read.textContent=m==='distance'?'Click points along the distance.':'Click polygon boundary vertices.'}
 click(e){if(!this.mode)return;this.coords.push([e.lngLat.lng,e.lngLat.lat]);this.sync();this.read.innerHTML=this.mode==='distance'?this.dist(this.coords):this.coords.length>=3?this.area(this.coords):`${this.coords.length} point${this.coords.length===1?'':'s'} selected.`}
 move(e){if(!this.mode||!this.coords.length)return;const c=[...this.coords,[e.lngLat.lng,e.lngLat.lat]];this.read.innerHTML=this.mode==='distance'?this.dist(c):c.length>=3?this.area(c):this.read.innerHTML}
 undo(){if(this.coords.length){this.coords.pop();this.sync()}}
 finish(){let f;if(this.mode==='distance'&&this.coords.length>=2)f=turf.lineString(this.coords,{name:'Measured distance'});if(this.mode==='area'&&this.coords.length>=3){const r=[...this.coords];r.push(r[0]);f=turf.polygon([r],{name:'Measured area'})}if(!f)return;this.features.push(f);this.coords=[];this.mode=null;this.box.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));this.sync();this.read.innerHTML=this.readFeature(f)}
 fc(){const fs=[...this.features];if(this.mode==='distance'&&this.coords.length>=2)fs.push(turf.lineString(this.coords,{preview:true}));if(this.mode==='area'&&this.coords.length>=2)fs.push(turf.lineString(this.coords,{preview:true}));this.coords.forEach((c,i)=>fs.push(turf.point(c,{preview:true,index:i})));return turf.featureCollection(fs)}
 sync(){const d=this.fc();this.maps.forEach(m=>{const s=m.getSource(this.src);if(s)s.setData(d)})}
 dist(c){if(c.length<2)return'Distance: click next point.';const km=turf.length(turf.lineString(c),{units:'kilometers'});return `<b>${km<1?(km*1000).toFixed(1)+' m':km.toFixed(3)+' km'}</b><br>${c.length} points`}
 area(c){if(c.length<3)return'Area: add more points.';const r=[...c,c[0]];const p=turf.polygon([r]);const sqm=turf.area(p),ha=sqm/10000,per=turf.length(turf.polygonToLine(p),{units:'kilometers'});return `<b>${ha.toFixed(3)} ha</b><br>${sqm.toFixed(0)} m² · perimeter ${per<1?(per*1000).toFixed(0)+' m':per.toFixed(2)+' km'}`}
 readFeature(f){return f.geometry.type==='LineString'?this.dist(f.geometry.coordinates):f.geometry.type==='Polygon'?this.area(f.geometry.coordinates[0].slice(0,-1)):(f.properties?.name||f.geometry.type)}
 clear(){this.features=[];this.coords=[];this.mode=null;this.rmMarkers();this.sync();this.read.textContent='Drawings cleared.'}
 edit(){this.rmMarkers();const i=[...this.features].map((f,i)=>[f,i]).reverse().find(x=>x[0].geometry.type==='Polygon');if(!i){this.read.textContent='No polygon available to edit.';return}const f=i[0],r=f.geometry.coordinates[0].slice(0,-1);r.forEach((c,vi)=>{const el=document.createElement('div');el.style.cssText='width:14px;height:14px;border-radius:50%;background:#ffb000;border:2px solid white;box-shadow:0 1px 4px #0008;cursor:move';const m=new maplibregl.Marker({element:el,draggable:true}).setLngLat(c).addTo(this.master);m.on('drag',()=>{const p=m.getLngLat();r[vi]=[p.lng,p.lat];f.geometry.coordinates[0]=[...r,r[0]];this.sync();this.read.innerHTML=this.readFeature(f)});this.markers.push(m)});this.read.textContent='Drag orange vertices to edit the polygon.'}
 rmMarkers(){this.markers.forEach(m=>m.remove());this.markers=[]}
 async importFile(file){if(!file)return;try{let geo,n=file.name.toLowerCase();if(n.endsWith('.json')||n.endsWith('.geojson'))geo=JSON.parse(await file.text());else if(n.endsWith('.kml'))geo=toGeoJSON.kml(new DOMParser().parseFromString(await file.text(),'text/xml'));else if(n.endsWith('.kmz')){const z=await JSZip.loadAsync(await file.arrayBuffer()),names=Object.keys(z.files).filter(x=>x.toLowerCase().endsWith('.kml'));if(!names.length)throw Error('KMZ contains no KML');geo=toGeoJSON.kml(new DOMParser().parseFromString(await z.files[names[0]].async('text'),'text/xml'))}else throw Error('Unsupported file type');const fs=geo.type==='FeatureCollection'?geo.features:[geo];this.features.push(...fs.filter(f=>f&&f.geometry));this.sync();if(this.features.length){const b=turf.bbox(turf.featureCollection(this.features));this.master.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:50,maxZoom:19})}this.read.textContent=`Imported ${fs.length} feature${fs.length===1?'':'s'}.`}catch(e){this.read.textContent='Import failed: '+e.message}}
 exportJSON(){if(!this.features.length)return this.read.textContent='Nothing to export.';dl(new Blob([JSON.stringify(turf.featureCollection(this.features),null,2)],{type:'application/geo+json'}),this.base+'.geojson')}
 exportKML(){if(!this.features.length)return this.read.textContent='Nothing to export.';const ps=this.features.map((f,i)=>{const nm=esc(f.properties?.name||`Feature ${i+1}`);if(f.geometry.type==='LineString'){const c=f.geometry.coordinates.map(x=>`${x[0]},${x[1]},0`).join(' ');return `<Placemark><name>${nm}</name><LineString><coordinates>${c}</coordinates></LineString></Placemark>`}if(f.geometry.type==='Polygon'){const c=f.geometry.coordinates[0].map(x=>`${x[0]},${x[1]},0`).join(' ');return `<Placemark><name>${nm}</name><Polygon><outerBoundaryIs><LinearRing><coordinates>${c}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>`}if(f.geometry.type==='Point'){const c=f.geometry.coordinates;return `<Placemark><name>${nm}</name><Point><coordinates>${c[0]},${c[1]},0</coordinates></Point></Placemark>`}return''}).join('');dl(new Blob([`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>${ps}</Document></kml>`],{type:'application/vnd.google-earth.kml+xml'}),this.base+'.kml')}
}
g.SSAMapTools=SSAMapTools})(window);